---
title: Nikolay Georgiev's Notes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: https://nikolayhg.github.io/notes
description: My notes
github_repo: notes
github_username: nikolayhg
theme_color: light
remote_theme: broccolini/athena
permalink: pretty
markdown: kramdown
